module.exports = {
  products: [
    {
      _id: "1",
      name: "Pothos Devil's Ivy",
      category: "pothos",
      image: "../asset/product/plant_1.jpg",
      price: 40,
      countInStock: 660,
      discription: "Very Good plants",
    },
    {
      _id: "2",
      name: "Cactus Cereus",
      category: "cactus",
      image: "../asset/product/plant_2.jpg",
      price: 60,
      countInStock: 666,
      discription: "Very Good plants",
    },
    {
      _id: "3",
      name: "Monstera Deliciosa",
      category: "monstera",
      image: "../asset/product/plant_3.jpg",
      price: 20,
      countInStock: 666,
      discription: "Very Good plants",
    },
    {
      _id: "4",
      name: "Monstera Borsigniana",
      category: "monstera",
      image: "../asset/product/plant_4.jpg",
      price: 20,
      countInStock: 668,
      discription: "Very Good plants",
    },
    {
      _id: "5",
      name: "Cactus Saguaro",
      category: "cactus",
      image: "../asset/product/plant_5.jpg",
      price: 220,
      countInStock: 666,
      discription: "Very Good plants",
    },
    {
      _id: "6",
      name: "Calathea Freddie",
      category: "calathea",
      image: "../asset/product/plant_6.jpg",
      price: 230,
      countInStock: 666,
      discription: "Very Good plants",
    },
    {
      _id: "7",
      name: "Calathea Beauty Queen",
      category: "calathea",
      image: "../asset/product/plant_7.jpg",
      price: 80,
      countInStock: 666,
      discription: "Very Good plants",
    },
    {
      _id: "8",
      name: "Pothos Pearls",
      category: "pothos Mejunla",
      image: "../asset/product/plant_8.jpg",
      price: 20,
      countInStock: 666,
      discription: "Very Good plants",
    },
    {
      _id: "9",
      name: "Monstera Variegata",
      category: "monstera",
      image: "../asset/product/plant_9.jpg",
      price: 20,
      countInStock: 666,
      discription: "Very Good plants",
    },
    {
      _id: "10",
      name: "Calathea Orbifolia",
      category: "calathea",
      image: "../asset/product/plant_10.jpg",
      price: 20,
      countInStock: 666,
      discription: "Very Good plants",
    },
  ],
};
